# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170611_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
