# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170611_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job_finished_date',
            field=models.DateTimeField(null=True),
        ),
    ]
