# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_task_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
