# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Urgent')], default=0),
        ),
    ]
